name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Download dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -o terraform-provider-mailtrap

    - name: Run tests
      run: go test -v ./...

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Download dependencies
      run: go mod download

    - name: Build for Linux
      run: GOOS=linux GOARCH=amd64 go build -o terraform-provider-mailtrap-linux-amd64

    - name: Build for macOS
      run: GOOS=darwin GOARCH=amd64 go build -o terraform-provider-mailtrap-darwin-amd64

    - name: Build for Windows
      run: GOOS=windows GOARCH=amd64 go build -o terraform-provider-mailtrap-windows-amd64.exe